### ISSUE TITLE
[Enhancement] Consider adding a NewDocuments.js to Studio 

### ISSUE THREAD

**Issue by rylanharper** [jjjuulliiaann/sanity-nuxt-3-starter#1]
First, this is awesome! I was a big fan of the Nuxt2/Sanity starter you made a while back and just found this repo today 💯

I was thinking that there could possibily be a `newDocuments.js` added to the studio for when a user clicks on the `Create New Document` button on the top left? It would be simple to implement:
```
{
  "name": "part:@sanity/base/new-document-structure",
  "path": "./src/utils/newDocuments.js" // or whatever path you consider best
}
```
And then within the `newDocuments.js` (not sure what should be "locked" or not):
```
import S from '@sanity/base/structure-builder'

// Document ids which:
// - cannot be created in the 'new document' menu
// - cannot be duplicated, unpublished or deleted
const LOCKED_DOCUMENT_IDS = [
  'pageHome',
  'siteNavigation',
  'siteOptions'
]

// Document types which:
// - cannot be created in the 'new document' menu
// - cannot be duplicated, unpublished or deleted
const LOCKED_DOCUMENT_TYPES = ['media.tag']

export default [
  // Use default values, but filter out templates of certain document types
  ...S.defaultInitialValueTemplateItems().filter((template) => {
    const { spec } = template
    return ![
      // Hide locked documents from 'create new document' menu
      ...LOCKED_DOCUMENT_IDS,
      ...LOCKED_DOCUMENT_TYPES
    ].includes(spec.id)
  })
]
```

**Comment by jjjuulliiaann** [comment]
Happy to hear you found the repo useful! And thanks for the suggestion, this is really helpful => I added it in 4687b32bb040c486be158a4cca4767572401c3e5

In the past I always removed "create", "delete" from the experimental actions in those documents after I created them, but this makes more sense.
