### ISSUE TITLE
Question with nuxt generate/preview

### ISSUE THREAD

**Issue by BenPam** [jjjuulliiaann/sanity-nuxt-3-starter#3]
Hi there,
I was having trouble setting my preview mode with sanity/nuxt, and I discovered (too late) your repo
I have set the preview part, but I'm still not getting the draft
So I'm guessing this can't be done with static nuxt-generate, can it ?

Anyway, thank you for your work !

**Comment by BenPam** [comment]
I just adjusted my project with your latest commit, and everything seems to be working perfectly.
Thanks again !

**Comment by jjjuulliiaann** [comment]
Great! I'm glad it worked :)
